sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: mvn install -U -DskipTests=true

script: mvn verify -U -Dmaven.javadoc.skip=true

after_success:
  - util/update_snapshot_docs.sh
  - util/deploy_snapshot.sh

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - secure: MJY016432HZC8lTgwtyWLzmjaKZNVxHWRZ1M3en4X4u0qsYd9mwpZKjbBry5M2GY1laeMwa2XX/hAicxaSqkijul6NGTkV1tSmAkRHccqyu80+5uQuK0SYRMzXPxZdHGwwYG1X9Myene7HDs2FyGg8UezQphfFQFk0y+0EFuFR4C2hrGUJl8OBjzx/sF9/MhyyUfdZPDHVxpZ/cmw+TspmBZ08IVjl5HJcYQGki/Y2VZ4d7rKfI24EeL5mjivFzWR3j6hWLKpRqbnCtMzcXDs/z8qBzWPIu8D+PZQpZwN6OQM/JDYpDD4Vn/9+FGStbjCGOtSTigvA7639NY7nKiGEWBJTEhREP+7YwovYcj9oPXodTYpNg/Ai1tgCHw2zGBiD2eandCCYhyN2gHcfdq2lJ1PA4nUPNdj1zsTW7IUNbAmJ+gVd4uDvgIML7NPqbgl9hUaEx/DPzVc272sOYJOdtRgcg5sOIA7Ehnky6CWnpKCggv2Lww3dO5bSeMccAoB96RQKNFqXTAynGoBaLZnVZzgCobZ66YAYWSosM0oBzWVwDEkw32MiRoizplF3NfnSARaGzENyCV4Gay611dbXYF9HVrxp3oYFnptEbvvOKmUGgp0HpQiBemzJ0tuabs4Zu47MkCnalrU9K8BkoreaVJk8WP0/KPj53t/fWVUT4=
  - secure: KHeXntBOn7rkumZmaxuVBzpmJzIrGmXdZh+Mr2D3Wlim9bAqLAvzIYI7ZW9Tpqlcq+2tWDgejJGttitGlAOCwiRkdauDvEZSSeNKv8zCXuYjUOPkSUaNYqLuQNuzfI8FU1lSjIRl50XZEp8fzItVGHw+1BjZ3x13V5fQwKaK8sgja25eUWuoselqKHgPSJxGJCcFBLRZP21FNvO5CMLJZvvWVFj/hM4gwCyvm/fl9Y4eqAbaj6SnfWALsJGkCF+wJ4tAkvHpRsXycl2jdqHG6oRnNNrzo/c9c3PMsc/pV1x6CIEJNwGwjp5FC0thcxKMOvXnS/QSJEGxTeXjMAgG47a37wsMd0zIttUui7fW+VrcfeF0i90CPi2u7ZQAJprobuDlA+1pGLbGVsWHuBICRqR4g/zXqS27UgiLMg3Qvfu63vFTNMV7ilbf8toItW2PFxPYx4ZapBYoV4/p9HHF20awnTvufgxWvIvkY9qU7edsT/XuW1T4FbumW9suJmJSELAKNaN152M2HWmFQLw1FneCY9sYPTRCpTvyW+O7MiQEC2kyOi2zevxQRoSRF8A1nMtXoi+pdteRHuR7Y9zbF22oeBO8RfAQLyP4m2zZ5krCzNZwcUc4q5o+X+NkZhyfZP7QK/YjKlYaqVHnYJtfE0FXDuilVHTPxkJ4gIa4HvE=
  - secure: mPxmpjRGGnm+g/Jx4C6vrnMfFpGQo6iaK7jXUbopByGiHj6THl1yZO+bx04VUY6buYP+e22tKtt05W4LcvJS2x/CVfdBWYa/mL3TuvtICNtsoaJlsZWSM329QcDLS8ycN6VjwgMmGLFik7jiGv1NnDA7DHD+CrkSzCl7dSaEuTx7+wk0/8bE3yox7n7qeNOhuTJueqlR+5MAN8wpFFVNpORDcBO1kG9TvE2SCkOO8LM+dA+7jjSNwqjejQPT2nZS7TErKCHqucysridk4GCHfS5LSKUA2gwdpJv6QR/j2frRnpGAzIbRcQwJw5o+joSLGhcbtSCsWJGuONEtfWAymaEvUD/ufOZePpDbhRyOuLtkR8MNMVYSkx5DS1P23tKbDjBbAzlknjT9Reo94sQKnMYrlYa38M8Y03hydzy2d/FNsgtqiOQaMYHbP6E1YJd02GjD6oBukxN3aUY8GUmpG5vam8ESUPzn/Fxuz3tfv9cFgg6ecwYSZ7UjFzJLjn1f0adbCieE4Ghl/O6y9O14NzLpIlRnWDcSCyEtkiDOLyXm11Kro5oaGY7RkAW3tM82fBfL8WZnk+freuVscWGm5a2mWHlsIn0j1egOZDZCEiW0Xio78fNYynyKc9O6jnZw5Vapeg5qkMOMijiDdh4AeSqKSfyi/OIbgb6qaAspfRY=

branches:
  except:
    - gh-pages
